# Generated by Django 3.2.5 on 2023-02-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogdtl', '0002_auto_20230209_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('draft', 'Draft')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
